// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9xukhXu0evlDX2uZrU8jHNUbUKwrDCPw',
    appId: '1:800237617336:web:8e90c18efea8d5db76744d',
    messagingSenderId: '800237617336',
    projectId: 'pushnotiutility',
    authDomain: 'pushnotiutility.firebaseapp.com',
    storageBucket: 'pushnotiutility.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyIfIKAxiMXIvdJsvCd3l0-QM_A-GSL68',
    appId: '1:800237617336:android:0e8110b820d9ac9476744d',
    messagingSenderId: '800237617336',
    projectId: 'pushnotiutility',
    storageBucket: 'pushnotiutility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjS0FLFwjltFHMB635cYwIhXTRQWPOrr0',
    appId: '1:800237617336:ios:f848648baf4f26ba76744d',
    messagingSenderId: '800237617336',
    projectId: 'pushnotiutility',
    storageBucket: 'pushnotiutility.appspot.com',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjS0FLFwjltFHMB635cYwIhXTRQWPOrr0',
    appId: '1:800237617336:ios:bc5f394a2e5ec9b676744d',
    messagingSenderId: '800237617336',
    projectId: 'pushnotiutility',
    storageBucket: 'pushnotiutility.appspot.com',
    iosBundleId: 'com.example.healthCareApp.RunnerTests',
  );
}
